### ISSUE TITLE
Compilation issue

### ISSUE THREAD

**Issue by dpryan79** [tolkit/fasta_windows#10]
While rebuilding fasta_windows on Bioconda I ran into the following compilation error:

```   Compiling fasta_windows v0.2.3 (/opt/conda/conda-bld/fasta_windows_1659449294535/work)
error[E0599]: no method named `progress_chars` found for enum `Result` in the current scope
  --> src/fw.rs:50:10
   |
50 |         .progress_chars(">>-");
   |          ^^^^^^^^^^^^^^ method not found in `Result<ProgressStyle, TemplateError>`
```

**Comment by Euphrasiologist** [comment]
That's interesting; thank you for raising the issue!

What platform/machine are you running on? And which version of fasta_windows?

**Comment by Euphrasiologist** [comment]
Actually, just had a quick google. Does this help?

You need to use the --locked flag as in `cargo install --locked xwin`, cargo has a [longstanding bug](https://github.com/Jake-Shadle/xwin/issues/26) where the lockfile is completely ignored without that flag. I've updated the README because I always forget about this until someone files a bug. Sorry for the inconvenience.

This might help, although a screenshot of the error would be helpful too :)

**Comment by dpryan79** [comment]
That solved the problem, thanks!
